language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=3.2.*

sudo: false

matrix:
  fast_finish: true

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
  - php composer.phar update --prefer-stable --prefer-lowest

notifications:
  email:
    - manuel.gomez@urbanara.com
